### ISSUE TITLE
Mix of English and Dutch with "what's the date"

### ISSUE THREAD

**Issue by timonvanhasselt** [OpenVoiceOS/skill-ovos-date-time#70]
I have a mix of English and Dutch at the moment when asking for the date (bold italic = Dutch)
 
wat voor dag is het morgen                                                
-->  _**Het is**_ thursday, november seventh, twenty twenty four, _**over één**_ day     
 
 wat voor dag is het vandaag  
--> _**Het is**_ wednesday, november sixth, twenty twenty four
 
 In the GUI I see the English date.
 
 Time works fine.
 I've updated the dialogs and intents for time & date in Gitlocalize, so maybe it's solved when these PR's are approved.

**Comment by JarbasAl** [comment]
is this still an issue? skill moved to https://github.com/OpenVoiceOS/ovos-date-parser instead of lingua-franca

**Comment by timonvanhasselt** [comment]
It's solved with the latest updates! Only the Home Screen GUI shows the day in English notation. 
My mycroft.conf

```
│ lang                                                         │ nl-nl                                                                 │
│ secondary_langs                                              │ []                                                                    │
│ system_unit                                                  │ metric                                                                │
│ temperature_unit                                             │ celsius                                                               │
│ windspeed_unit                                               │ m/s                                                                   │
│ precipitation_unit                                           │ mm                                                                    │
│ time_format                                                  │ full                                                                  │
│ spoken_time_format                                           │ full                                                                  │
│ date_format                                                  │ DMY 
```

**Comment by JarbasAl** [comment]
then thats a homescreen skill issue, closing this one!
